FROM python:3.7-slim
RUN apt update && apt install -y \
    python3-dev \
    python3-pip \
    ffmpeg \
    curl
COPY ./requirements.txt /usr/local/src/yt2spec/
RUN pip3 install -r /usr/local/src/yt2spec/requirements.txt
RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl
COPY . /usr/local/src/yt2spec/
WORKDIR /usr/local/src/yt2spec/
ENV PYTHONPATH="${PYTHONPATH}:/usr/local/src/yt2spec/yt2spec"